[package]
name = "bevy_input_actionmap"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
license = "mit"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5", default-features = false }
ron = { version = "*", optional = true }
serde = { version = "*", optional = true }

[dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["bevy_winit", "x11"] }

[features]
serialize = ["ron", "bevy/serialize", "serde"]